#!/usr/bin/env bash
set -euo pipefail

# Ensure standard paths are available (CodeDeploy runs with minimal PATH)
export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

APP_DIR="/opt/documenso"
ENV_FILE="${APP_DIR}/.env"

# Determine environment from CodeDeploy deployment group name
DEPLOYMENT_GROUP="${DEPLOYMENT_GROUP_NAME:-staging}"

if echo "$DEPLOYMENT_GROUP" | grep -qi "production"; then
  ENV_NAME="production"
else
  ENV_NAME="staging"
fi

echo "[Deploy] Fetching secrets for environment: ${ENV_NAME}"

# AWS region (override via instance tag or env var)
REGION="${AWS_REGION:-eu-central-1}"

# ---------------------------------------------------------------
# App secrets (your own secret with a friendly name)
# ---------------------------------------------------------------
APP_SECRET_ID="documenso/${ENV_NAME}/app"
APP_SECRETS=$(aws secretsmanager get-secret-value \
  --secret-id "$APP_SECRET_ID" \
  --query 'SecretString' \
  --output text \
  --region "$REGION")

# ---------------------------------------------------------------
# RDS credentials (AWS-managed secret — ARN comes from app secret)
# The app secret must contain a key "RDS_SECRET_ARN" pointing to
# the actual AWS-managed RDS secret ARN.
# ---------------------------------------------------------------
RDS_SECRET_ARN=$(echo "$APP_SECRETS" | jq -r '.RDS_SECRET_ARN // empty')

if [ -z "$RDS_SECRET_ARN" ]; then
  echo "[Deploy] ERROR: RDS_SECRET_ARN not found in app secret. Cannot build DATABASE_URL."
  exit 1
fi

DB_SECRETS=$(aws secretsmanager get-secret-value \
  --secret-id "$RDS_SECRET_ARN" \
  --query 'SecretString' \
  --output text \
  --region "$REGION")

# Parse RDS credentials
DB_HOST=$(echo "$DB_SECRETS" | jq -r '.host')
DB_PORT=$(echo "$DB_SECRETS" | jq -r '.port // "5432"')
DB_USER=$(echo "$DB_SECRETS" | jq -r '.username')
DB_PASS=$(echo "$DB_SECRETS" | jq -r '.password')

# DB name: read from app secret, fall back to the dbname in the RDS secret,
# fall back to "documenso_<env>"
DB_NAME=$(echo "$APP_SECRETS" | jq -r '.DB_NAME // empty')
if [ -z "$DB_NAME" ]; then
  DB_NAME=$(echo "$DB_SECRETS" | jq -r '.dbname // empty')
fi
if [ -z "$DB_NAME" ]; then
  DB_NAME="documenso_${ENV_NAME}"
fi

# URL-encode the password (handles special chars)
DB_PASS_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${DB_PASS}', safe=''))")
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS_ENCODED}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

# ---------------------------------------------------------------
# Write .env — values are JSON-quoted for shell safety
# ---------------------------------------------------------------
echo "[Deploy] Writing .env file..."
{
  echo "# Auto-generated by deployment — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Environment: ${ENV_NAME}"
  echo ""

  # Write each key=value from app secret, JSON-quoting the value
  # Skip RDS_SECRET_ARN — it's only used during deploy
  echo "$APP_SECRETS" | jq -r '
    to_entries[]
    | select(.key != "RDS_SECRET_ARN")
    | "\(.key)=\(.value | @json)"
  '

  echo ""
  echo "# Database (from RDS secret)"
  echo "NEXT_PRIVATE_DATABASE_URL=\"${DATABASE_URL}\""
  echo "NEXT_PRIVATE_DIRECT_DATABASE_URL=\"${DATABASE_URL}\""

  # Ensure NODE_ENV is present
  if ! echo "$APP_SECRETS" | jq -e '.NODE_ENV' > /dev/null 2>&1; then
    echo "NODE_ENV=\"production\""
  fi
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "[Deploy] Secrets written to .env (${ENV_NAME})"
